---
- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present 
  become: yes

- name: Install Linuxbrew prerequisites for Red Hat or CentOS
  yum:
    update_cache: yes
    pkg: "{{ item }}"
    state: installed
  with_items:
    - curl 
    - file 
    - git 
    - python-setuptools
  become: yes

- name: Install linuxbrew with git
  become: no
  git: 
    repo: https://github.com/Linuxbrew/brew.git 
    dest: ~/.linuxbrew
    clone: yes
    depth: 1
    accept_hostkey: yes
    update: no

- name: Symlink brew to homebrew_brew_bin_path.
  file:
    src: "/home/{{ansible_user}}/.linuxbrew/bin/brew"
    dest: "/usr/local/bin/brew"
    state: link
  become: yes

- name: Force update brew after installation.
  become: no
  command: "/usr/local/bin/brew update --force"